### ISSUE TITLE
[BUG] Stutter in passthrough mode due to no reply from motor  

### ISSUE THREAD

**Issue by nbatham** [FourierDynamics/fourier-cpp-sdk#1]
**DESCRIPTION**
When using FSA80-20-120P motors with the C++ library (V0.7.0), the motors occasionally do not return a value when addressed by the setInputPositionPt() function. The setInputPositionPt() function then waits for a 500ms timeout and is blocking, thus resulting in a strong jerk in the motor’s motion (when controlled with a trajectory).

This behaviour also occurs while using the equivalent function in the fw-v2.0 branch of the python library.

**EXPECTED BEHAVIOUR**
The setInputPositionPt() funtion should only wait a few ms for a response, the produce an error, instead of waiting a full 500ms. 

**ACTUAL BEHAVIOUR**
The setInputPositionPt() requires a response for every command sent and waits a full 500ms. This means that during a trajectory the motors will stop. This issue is amplifed when multiple motors are attached as more messages are lost, each triggering a timeout and blocking commands to all motors.

**POTENTIAL FIX**
Ideally, both:

- * Expose the timeout variable for setInputPositionPt(), including a no wait option (0 timeout)
- * Resolve the absence of feedback sent by the firmware if possible"

The same problem occurs when using setInputPosition_pt() in the fw-v2.0 branch of the python library. In that case, removing the try-catch block that waits for feedback (lines 939-945 of aios.py) does fix the issue.

**STEPS TO REPRODUCE**
1. Connect a FSA80-20-120P
2. Generate a trajectory of N points
3. Loop through the trajectory using the setInputPositionPt() command
4. Monitor for any timeout errors

Note: The timeout errors can occur randomly, but generally with a frequence of approximately one every 1-10 seconds

**Comment by vcrocher** [comment]
The update in the branch seems to solve the issue.
Still, currently the timeout for command can only be set at group creation and the `void enable(const std::vector<float> &status);` requires a quite long time to succeed (~120ms), so the timeout cannot be effectively set to less than 120ms.

To fix this, would it possible to have a ` bool sendCommand(const GroupCommand &group_command);` which takes an additional timeout parameter, in a similar fashion as the `bool getNextFeedback(GroupFeedback &feedback, int32_t timeout_ms = DEFAULT_TIMEOUT_MS);` ? With such method, it would be possible to define a large timeout for the enabling and reduce it to 5ms or so for the commands.

Also, note there are still verbose debug prints coming from the library which are not controlled by spdlog. See example below:

**Comment by lvhao54** [comment]
@vcrocher 
You can set the timeout to 10ms.Then wait 200ms after sending the enable.`std::this_thread::sleep_for(std::chrono::milliseconds(200));`
The enable command execution time will be optimized in version v0.8.0.
All prints is controlled by spdlog in next version.
